#!/usr/bin/env python3

from eval import *
from sys import argv

global_env = Env({
	"Object": ObjectClass,
	"Class": ClassClass,
	"print": lambda x: print(do_op("to_string", x)),
	"format": lambda x, *args: x.format(*args),
	"to_string": lambda x: do_op("to_string", x)
})
eval(ast.Import("prelude.oops"), global_env)

match len(argv):
	case 1:
		while True:
			try:
				string = input("> ")
			except KeyboardInterrupt:
				print()
				continue
			except EOFError:
				print()
				break
			try:
				tree = parse(string)
			except SyntaxError:
				tree = parse(string, "repl_exp")
			print(do_op("to_string", eval(tree, global_env)))
	case 2:
		with open(argv[1]) as file:
			eval(parse(file.read()), global_env)